spring:
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    by.taverna.shlyapnika: INFO
